app:
  PageSize: 10
  JwtSecret: 233
  PrefixUrl: http://127.0.0.1:8081

  RuntimeRootPath: runtime/

  ImageSavePath: upload/images/
  # MB
  ImageMaxSize: 5
  ImageAllowExts: .jpg,.jpeg,.png

  ExportSavePath: export/
  QrCodeSavePath: qrcode/
  FontSavePath: fonts/

  LogSavePath: logs/
  LogSaveName: log
  LogFileExt: log
  TimeFormat: 20060102

server:
  #debug or release
  RunMode: debug
  HttpPort: 8081
  ReadTimeout: 60
  WriteTimeout: 60

database:
  Type: mysql
  User: root
  Password: 3sqrcizt
  Host: localhost:3307
  Name: blog
  TablePrefix: blog_

redis:
  Host: localhost:6380
  Password: 3sqrcizt
  IdleTimeout: 200